spring.application.name=farm_leftover

#PostgreSQL by aiven.io
spring.datasource.url=${AIVEN_URL}

#Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

#Jwt
#jwt.secret.key=${JWT_SECRET_KEY}
jwt.accessTokenExpirationMinutes=1
jwt.refreshTokenExpirationDays=7

spring.mvc.problem-details.enabled=true
spring.mvc.problemdetails.enabled=true

spring.jpa.properties.jakarta.persistence.lock.timeout=30000

cloudinary.url=${CLOUDINARY_URL}