spring.application.name=farm_leftover

#PostgreSQL by aiven.io
spring.datasource.url=${AIVEN_URL}

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#Jwt
#jwt.secret.key=${JWT_SECRET_KEY}
jwt.accessTokenExpirationMinutes=1
jwt.refreshTokenExpirationDays=7

spring.mvc.problem-details.enabled=true
spring.mvc.problemdetails.enabled=true



#Google geocoding api
google.api.key=${GOOGLE_API_KEY}


cloudinary.url=${CLOUDINARY_URL}
