spring.application.name=farm_leftover

#PostgreSQL by aiven.io
spring.datasource.url=${AIVEN_URL}

#Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

#Jwt
#jwt.secret.key=${JWT_SECRET_KEY}
jwt.accessTokenExpirationMinutes=1
jwt.refreshTokenExpirationDays=7

spring.mvc.problem-details.enabled=true
spring.mvc.problemdetails.enabled=true

#PayPal
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=10027
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=false

#Google geocoding api
google.api.key=${GOOGLE_API_KEY}

#Cloudinary Images
cloudinary.url=${CLOUDINARY_URL}
